security:
    encoders:
        Nucleos\UserBundle\Model\UserInterface: auto

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        nucleos_userbundle:
            id: nucleos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            user_checker: Nucleos\UserBundle\Security\UserChecker
            form_login:
                provider: nucleos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/change-password, role: IS_AUTHENTICATED_REMEMBERED }
        # If you have an admin backend, uncomment the following line
        # - { path: ^/admin/, role: ROLE_ADMIN }
