security:

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    firewalls:
        main:
            pattern: ^/
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/change-password, role: IS_AUTHENTICATED_REMEMBERED }
        # If you have an admin backend, uncomment the following line
        # - { path: ^/admin/, role: ROLE_ADMIN }
