version: '3.1'
services:
  #apache_ms_user_reg:
    #build: './apache/'
    #depends_on:
      #- php_ms_user_reg
    #ports:
      #- "8080:80"
    #volumes:
      #- ../mongoDB_symfony_user_reg_app_back:/var/www/html/ms_user_reg/back

  nginx_ms_user_reg:
    image: nginx:1.17
    container_name: mongoDB_symfony_user_reg_app_nginx
    depends_on:
      - php_ms_user_reg
    volumes:
      - ../mongoDB_symfony_user_reg_app_back:/var/www/ms_user_reg/back
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80

  php_ms_user_reg:
    build: ./php
    container_name: mongoDB_symfony_user_reg_app_php
    volumes:
      - ../mongoDB_symfony_user_reg_app_back:/var/www/ms_user_reg/back
  
  mongodb_ms_user_reg:
        image: mongo:latest
        container_name: mongodb
        hostname: mongodb
        volumes:
            - ./mongodb/mongod.conf:/etc/mongod.conf
            - ./mongodb/initdb.d/:/docker-entrypoint-initdb.d/
            - ./mongodb/data/db/:/data/db/
            - ./mongodb/data/log/:/var/log/mongodb/
        env_file:
            - ./.env
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
            MONGO_INITDB_USER: ${MONGO_INITDB_USERNAME}
            MONGO_INITDB_PWD: ${MONGO_INITDB_PASSWORD}
        ports:
            - "27017:27017"
        command: ["-f", "/etc/mongod.conf"]
